services:
  mydb:
    container_name: mydb
    image: postgres
    environment:
      - POSTGRES_USER=21savage
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    
    networks:
      - daun-net
    ports:
      - ":5432"
       
  main:
    build: ./app/main
    image: hoochie/main:latest
    ports:
      - "81:80"
    container_name: main
    depends_on:
      - mydb
    restart: always
    volumes:
      - /home/savage21/hardWork/go/store/store/app/main/internal/templates/html:/app/internal/templates/html
      - /home/savage21/hardWork/go/store/store/app/main:/app

    networks:
    - daun-net
       

  auth: 
    build: ./app/auth
    image: hoochie/auth:latest
    ports:
      - "82:80"
    container_name: auth
    volumes:
      - /home/savage21/hardWork/go/store/store/app/auth:/app
    depends_on:
      - main
    restart: always
    networks:
    - daun-net
  admin:
    build: ./app/admin
    image: hoochie/admin:latest
    ports:
     - "83:80"
    container_name: admin
    volumes:
      - /home/savage21/hardWork/go/store/store/app/admin:/app
    depends_on:
      - mydb
    restart: always
    networks:
      - daun-net

       
  nginx:
    container_name: store_nginx
    build: ./app/nginx
    image: hoochie/nginx:latest
    depends_on:
      - auth
    restart: always
    ports :
      - "80:80"
    volumes:
    - /home/savage21/hardWork/go/store/store/app/nginx/html:/usr/share/nginx/html
    - /home/savage21/hardWork/go/store/store/app/nginx/conf:/etc/nginx/conf.d
    networks:
    - daun-net
       
  cash:
    build: ./app/redis
    container_name: cash
    image: hoochie/nginx:latest
    ports:
      - ":6379"
    restart: always
    volumes:
      - cash:/data
    networks:
    - daun-net
      
    


volumes:
  pgdata:
  cash:
networks:
  daun-net:
    driver: bridge 
  
  
