name: main deploy 
on:
  workflow_run:
    workflows:  ["main test"]
    types:
      - completed

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:

    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build new image
      run: |
        cd app/main
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/main:latest . 
    - name: push docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/main:latest
    - name: deploy to server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker compose pull
          docker compose up -d
          docker image prune -f