name: main test  

on:
  push:
    branches: dev
    paths:
      - "app/**"
    
  

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: get services
    - id: testiki
    - run: |
        chmod +x ./testy.sh
        ./testy.sh
    - name: testiki
      run: |
        services=(${{steps.testiki.outputs.services}})
        for dir in $services;do
          docker build -t $dir ./app/$dir
          docker exec -i $dir run go test ./...
          
        done
    

