name: main test  

on:
  push:
    branches: dev
    paths:
      - "app/**"
    
  

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: testiki
      run: |
        docker compose up --build -d
        services=($(docker ps --format "{{.Names}}"))
        echo "services:$serives"
        for dir in ${services[@]}; do
        if [ "$dir" != "cash" ] && [ "$dir" != "store_nginx" ] && [ "$dir" != "mydb" ]; then
          echo "container: $dir"
          docker exec -i "$dir" go test ./...
        fi
        done
    

