name: main test  

on:
  push:
    branches: dev
    paths:
      - "app/**"
    
  

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: testiki
      run: |
        docker compose up --build -d
        services=($(docker images --format "{{.Repository}}"))
        for dir in $services;do
          docker exec -i $dir run go test ./...
          
        done
    

